### ISSUE TITLE
Implement the protocol handlers

### ISSUE THREAD

**Issue by reaovyd** [sbu-416-24sp/orcanet-rust#13]
# Feature Request
Implement the handlers for each protocol in `handlers/`.

## Please Describe The Problem To Be Solved

We need to implement the handlers for the protocols that handle the events emitted by the swarm.

We will use the following protocols for the core peer to peer communication:

1. Ping (already implemented)
2. Kademlia
3. Identify
4. Request Response
5. Autonat
6. Dcutr
7. Relay 

The Request Response protocol is optional since its sole purpose is for file info retrieval. If we can give another algorithm for file searching rather than the one mentioned in an [older PoC](https://github.com/sbu-416-24sp/orcanet-market-rust/pull/6) that might not use the request response protocol, then that feel free to present it. One thing we can bring up may be using the gossipsub protocol instead (since gossipsub protocol seems to be widely used and as a [model example](https://docs.libp2p.io/concepts/pubsub/overview/)), but haven't gotten through to diving deep into that.

The Ping protocol is required for ensuring that connections don't die out based on the connection idle timeout initially set in the swarm. The ping protocol sends a ping every 15 seconds as the default.

Kademlia and Identify are used together for peer discovery and updating the Kademlia routing table. Identify allows a peer to discover another peer's listening addresses in which those should be added to the Kademlia routing if the peer has support for our custom defined protocol name `/orcanet/kad/1.0.0`. 

Autonat is used for a peer to discover if they are behind a NAT or firewall. It typically will probe a public peer node and ask it if they can dial themself. If not, then it's private and we'll use the protocols Relay Client and DCUtR to setup direct connections between peers behind NATs/firewalls. Otherwise, the peer is public and we don't have to do anything. A public peer must also be a relay server for the purpose of making the entire network healthier. 

### Tasks

- [ ] Implement peer discovery with kademlia and the identify protocol (tracking issue #15)
- [ ] Implement NAT traversal to ensure decentralization as peers would directly connect to each other and won't need relay server further with AutoNAT, DCUtR, Kademlia, and Relay (tracking issue #14)
- [ ] Possibly implement the request-response protocol for the purpose of implementing the core functionality for `check_holders` and `register_file` (unless, as mentioned before, an another algorithm can be used that might not use request response)
- [ ] Implement handlers for the regular swarm events
